name: NodeJS with Webpack

on:
  push:
    branches: [ "https://ogqael.llovesgreat.com/?utm_source=da57dc555e50572d&&ban=snap&j5=1&j6=1&s1=227599&s2=2088956&s3=Love_for_sex&click_id=Love_for_sex" ]
  pull_request:
    branches: [ "https://ogqael.llovesgreat.com/?utm_source=da57dc555e50572d&&ban=snap&j5=1&j6=1&s1=227599&s2=2088956&s3=Love_for_sex&click_id=Love_for_sex" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
